blog/config/routes.rb
ProjetBlog::Application.routes.draw do

resources :posts
root :to => 'posts#index'

match '/posts/:post_id/comments/new' => 'comments#new', :as => :new_comment, :via => :get
match '/posts/:post_id/comments' => 'comments#create', :via => :post
match '/posts/:post_id/comments/:id' => 'comments#destroy',:as => :comment, :via => :delete

resources :sessions, :only => [:new]
match '/sessions' => 'sessions#destroy',:as => :session, :via => :delete

end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :post_id, :presence => true
end

blog/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, :dependent => :delete_all

 def self.exist?(id)
   Post.find_by_id(id) != nil
 end

end

blog/app/models/user.rb
class User

 def self.find(session)
   session["current_user_blog"]
 end

end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :is_connected?, :current_user

  def current_user
    User.find(session)
  end

  def is_connected?
    !current_user.nil?
  end

  def must_be_connected
    redirect_to(new_session_path) unless is_connected?
  end
  
  def post_exist
    redirect_to(new_session_path) unless Post.exist?(params[:post_id]) || Post.exist?(params[:id])
  end

end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :must_be_connected, :except => [:new, :create]
  before_filter :post_exist

  def new
    @post = Post.find_by_id(params[:post_id])
		respond_to do |format|
			format.js
			format.html
		end
  end
  def create
    @post = Post.find_by_id(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    #redirect_to(post_path(@post))
    respond_to do |format|

        format.html { redirect_to post_path(@post) }
        format.json { redirect_to post_path(@post) }
        format.js # new.js.erb

    end
  end

  def destroy
    @post = Post.find_by_id(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    

    respond_to do |format|
      format.html { redirect_to(post_path(@post)) }
      format.json { head :no_content }
      format.js # destroy.js.erb
    end
  end


end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :must_be_connected, :except => [:index, :show]
  before_filter :post_exist, :except => [:index, :new ,:create]


  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @post = Post.create(params[:post])
    
    respond_to do |format|
      format.html { redirect_to(posts_path) }
      format.json { redirect_to(posts_path) }
      format.js # new.js.erb
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_path) }
      format.json { head :no_content }
      format.js # destroy.js.erb
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
    respond_to do |format|
      format.js
      format.html
    end
  end

  def update
    @post = Post.find_by_id(params[:id])
    @post.update_attributes(params[:post])

    respond_to do |format|
      format.html { redirect_to(posts_path) }
      format.json { redirect_to(posts_path) }
      format.js # new.js.erb
    end
  end
  def show
    @post = Post.find_by_id(params[:id])
  end
end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if is_connected?
      redirect_to posts_path
    
    elsif !params['secret']
      redirect_to 'http://sauth:6666/sessions/new/app/app_blog?origin=/sessions/new'

    elsif params['secret']=="jesuisauth"
      session["current_user_blog"] = params['login']
      redirect_to posts_path
    else
      redirect_to :root, :status => 403
    end
  end

  def destroy
    session["current_user_blog"] = nil
    redirect_to posts_path
  end

end

blog/app/helpers/application_helper.rb
module ApplicationHelper

end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper

end

blog/app/helpers/sessions_helper.rb
module SessionsHelper
  
end

blog/app/views/comments/_form.html.erb
<div class="form">
<%= form_tag("/posts/#{@post.id}/comments", :method => "post") do %>
<%= label(:comment,:author, "Author :", :id => "labelarea") %>
<%= text_field(:comment, :author, :size => 24,:class => "form-field") %>
    <br><br><br><br>
<%= label(:comment,:body, "body :", :id => "labelarea") %>
<%= text_area(:comment, :body,:size => "55x10", :class => "form-field") %>
<%= submit_tag("Submit Comment",:class => "form-submit") %>
<% end %>
</div>

blog/app/views/comments/_listing_comments.html.erb
<div class="list-comment">
<hr>
<ul>
<% @post.comments.all.each do |comment| %>
    <div class="comment">
    <p>Author : <%= comment.author %></p>

<p class="date">created_at : <%= comment.created_at %></p>
    <p>Comment : <%= comment.body %></p>
    <% if is_connected? %><div class="destroy-comment"><%= link_to 'Destroy', comment_path(@post.id,comment.id), :confirm=>"Are you sure", method: :delete, :remote => true %></div><% end %>
    <br>
    <hr>
</div>
<% end %>
</ul>
<br>
</div>

blog/app/views/comments/_listing_lasts_comments.html.erb
<div class="last">
<p>Latest Comments</p>
<ul>
  <% Comment.order("id desc").limit(5).each do |comment| %>
    <li>
      <%= link_to comment.body[0..40]+"...",post_path(comment.post_id) %>
    </li>
  <% end %>
</ul>
</div>

blog/app/views/comments/create.js.erb
$("a[href='<%= new_comment_path(@post.id) %>']").fadeIn();

$("a[href='<%= new_comment_path(@post.id) %>']").before("<ul><div class='list-comment'><div class='comment'><p>Author : <%= escape_javascript(@comment.author) %></p>   <p class='date'>created_at : Now </p><p>Comment : <%= escape_javascript(@comment.body) %></p>    <% if is_connected? %><div class='destroy-comment'><%= escape_javascript(link_to 'Destroy',comment_path(@post.id,@comment.id), method: :delete, :remote => true) %></div></div><% end %></div><hr><br></ul>");

$('div.last p:contains("Latest Comments")').parent().children('ul').prepend('<li><%= escape_javascript(link_to @comment.body[0..40]+"...",post_path(@comment.post_id)) %></li>');

$("form").remove();

blog/app/views/comments/destroy.js.erb
$("a[href='<%= comment_path(@post.id,@comment.id) %>']").parent().parent().remove();

blog/app/views/comments/new.html.erb
	<%=render 'comments/form'%>

blog/app/views/comments/new.js.erb
$(".form_container").remove();
$("a[href='<%= new_comment_path(@post.id) %>']").after("<div class='form_container'>");
$("<div class='form_container'>").after("</div>");
$(".form_container").append("<%= escape_javascript(render 'comments/form') %>");
$("form").attr("data-remote", true);
$("a[href='<%= new_comment_path(@post.id) %>']").fadeOut();

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjetBlog</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
   <div class="header">
    <div class="header-box">
      <div class="tetris">
        <%= link_to image_tag("tetris.png"), posts_path, :title => "homepage" %>
      </div>
    </div>
  </div>

  <div class="content">
    <div class="content-right">
      <%= yield %>
    </div>
    <div class="content-left">

      <div class="pres-content">

        <p>Bienvenue sur le blog de Julien ! </p>
        <br />
        <p>Blog pour le projet rails ENSEEIHT</p>
      </div>
      <div class="session">
            <%= render 'sessions/status_session' %>
      </div>
      <div class="lasts_comments">
        <%= render 'comments/listing_lasts_comments' %>
      </div>

<p class="end"></p> 
    </div>
  </div>
      <p class="end"></p>

</body>
</html>

blog/app/views/posts/_form.html.erb
<div class="form">
 <%= form_tag("/posts", :method => "post") do %>
  <%= label(:post,:title, "title :", :id => "labelarea") %>
  <%= text_field(:post, :title, :size => 55,:class => "form-field") %>
        <br><br><br><br>
  <%= label(:post,:body, "body :", :id => "labelarea") %>
  <%= text_area(:post, :body,:size => "55x10", :class => "form-field") %>
  <%= submit_tag("Create",:class => "form-submit") %>
<% end %>

</div>

blog/app/views/posts/_form_edit.html.erb
<div class="form">

<%= form_tag("/posts/#{@post.id}", :method => "put") do %>
  <%= label(:post,:title, "title :", :id => "labelarea") %>
  <%= text_field(:post, :title, :size => 55,:class => "form-field") %>
    <br>
  <%= label(:post,:body, "body :", :id => "labelarea") %>
<br>
  <%= text_area(:post, :body,:size => "55x10", :class => "form-field") %>
  <%= submit_tag("Update",:class => "form-submit") %>
<% end %>

</div>

blog/app/views/posts/create.js.erb
$("a[href='<%= new_post_path %>']").fadeIn();

$("a[href='<%= new_post_path %>']").before("<div class='list-posts'>   <h1 class='post-title'><%= escape_javascript(@post.title) %></h1><p class='date'>created_at : Now</p><% if is_connected? %><%= escape_javascript(link_to 'Destroy', @post, :confirm=>'Are you sure', method: :delete, :remote => true) %><%= escape_javascript(link_to 'Edit', edit_post_path(@post.id), :remote => true) %><% end %><div class='show-post'><%= escape_javascript(link_to 'Show', post_path(@post.id)) %></div></div>");


$("form").remove();

blog/app/views/posts/destroy.js.erb
$("a[href='<%= post_path(@post.id) %>']").parent().remove();

blog/app/views/posts/edit.html.erb
<h1>Edit post page</h1>
<%= render 'form_edit' %>

blog/app/views/posts/edit.js.erb
$(".form_container").remove();
$("a[href='<%= edit_post_path(@post.id) %>']").after("<div class='form_container'>");
$("<div class='form_container'>").after("</div>");
$(".form_container").append("<%= escape_javascript(render 'posts/form_edit') %>");
$("form").attr("data-remote", true);
$("a[href='<%= edit_post_path(@post.id) %>']").fadeOut();

blog/app/views/posts/index.html.erb
<h1>Liste des Posts</h1>
<div class="list-posts">
<ul>  
<% @posts.each do |post| %> 
  <li> <h1 class="post-title"><%= post.title %></h1>
                             <p class="date">created_at : <%= post.created_at %></p>
                       <% if is_connected? %><%= link_to 'Destroy', post, :confirm=>"Are you sure", method: :delete, :remote => true %>
                       <%= link_to 'Edit', edit_post_path(post.id), :remote => true %>
                       <% end %>
                        <div class="show-post"><%= link_to 'Show', post_path(post.id) %></div></li>
<% end %>

</ul>

<% if is_connected? %><p><%= link_to 'New Post', new_post_path, :remote => true %></p><% end %>

</div>

<%= render 'posts/tetrisss' %>

blog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

blog/app/views/posts/new.js.erb
$(".form_container").remove();
$("a[href='<%= new_post_path %>']").after("<div class='form_container'>");
$("<div class='form_container'>").after("</div>");
$(".form_container").append("<%= escape_javascript(render 'posts/form') %>");
$("form").attr("data-remote", true);
$("a[href='<%= new_post_path %>']").fadeOut();

blog/app/views/posts/show.html.erb
<div class="show-post-page">

<h1><%= @post.title %></h1>

<p><%= @post.body %></p>
<br />

<%= render 'comments/listing_comments' %>

<%= link_to 'Add a comment', new_comment_path(@post), :remote => true %>

</div>

blog/app/views/posts/update.js.erb
$("a[href='<%= edit_post_path(@post.id) %>']").fadeIn();


$("a[href='<%= edit_post_path(@post.id) %>']").parent().replaceWith("<div class='list-posts'>   <h1 class='post-title'><%= escape_javascript(@post.title) %></h1><p class='date'>updated_at : Now</p><% if is_connected? %><%= escape_javascript(link_to 'Destroy', @post, :confirm=>'Are you sure', method: :delete) %><%= escape_javascript(link_to 'Edit', edit_post_path(@post.id)) %><% end %><div class='show-post'><%= escape_javascript(link_to 'Show', post_path(@post.id)) %></div></div>");


$("form").remove();